// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20240504095854_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Entities.Concrete.CPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseClockSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoreCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntegratedGraphics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxTurboFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemorySupport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tdp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27eac8e5-59bf-41d5-830b-6a5b5131b5b4"),
                            BaseClockSpeed = "3.3 GHz",
                            Brand = "Intel",
                            CacheSize = "12 MB",
                            CoreCount = 4,
                            IntegratedGraphics = "Intel UHD Graphics 730",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.3 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i3-12100",
                            Price = 129.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "60W",
                            ThreadCount = 8
                        },
                        new
                        {
                            Id = new Guid("44c4e17f-3f9c-433c-b9b5-3b7fbf771154"),
                            BaseClockSpeed = "4.0 GHz",
                            Brand = "AMD",
                            CacheSize = "40 MB",
                            CoreCount = 4,
                            IntegratedGraphics = "AMD Radeon Graphics Vega 6",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.6 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 3 5300G",
                            Price = 149.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 8
                        },
                        new
                        {
                            Id = new Guid("d00b83c3-6ef2-422f-88e8-883b95dfd0c0"),
                            BaseClockSpeed = "2.5 GHz",
                            Brand = "Intel",
                            CacheSize = "18 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "Intel UHD Graphics 770",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.4 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i5-12400",
                            Price = 229.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("1ca9f9a0-cb57-40ed-ab19-31f0bf0a9647"),
                            BaseClockSpeed = "3.7 GHz",
                            Brand = "AMD",
                            CacheSize = "38 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.6 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 5 5600X",
                            Price = 299.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("13cab3be-62ca-4b99-9440-d0748611876d"),
                            BaseClockSpeed = "3.6 GHz",
                            Brand = "Intel",
                            CacheSize = "25 MB",
                            CoreCount = 8,
                            IntegratedGraphics = "Intel UHD Graphics 770",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "5.2 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i7-12700K",
                            Price = 439.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "125W",
                            ThreadCount = 16
                        },
                        new
                        {
                            Id = new Guid("4bbd9ac1-2d10-4746-b66c-8973191466fc"),
                            BaseClockSpeed = "3.7 GHz",
                            Brand = "AMD",
                            CacheSize = "64 MB",
                            CoreCount = 12,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2020, 11, 19),
                            MaxTurboFrequency = "4.8 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 9 5900X",
                            Price = 549.99000000000001,
                            SocketType = "AM4",
                            Tdp = "105W",
                            ThreadCount = 24
                        },
                        new
                        {
                            Id = new Guid("a821c299-0749-4078-be86-e8522132fba7"),
                            BaseClockSpeed = "3.5 GHz",
                            Brand = "Intel",
                            CacheSize = "20 MB",
                            CoreCount = 8,
                            IntegratedGraphics = "Intel UHD Graphics 770",
                            LaunchDate = new DateOnly(2021, 3, 18),
                            MaxTurboFrequency = "5.3 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i9-11900K",
                            Price = 499.99000000000001,
                            SocketType = "LGA 1200",
                            Tdp = "125W",
                            ThreadCount = 16
                        },
                        new
                        {
                            Id = new Guid("000fb8a0-bb82-430b-a701-9704d52d62cd"),
                            BaseClockSpeed = "3.5 GHz",
                            Brand = "AMD",
                            CacheSize = "32 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "AMD Radeon Graphics",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.5 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 5 7600",
                            Price = 229.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("824663d5-8b1c-4416-9843-c1c2af263e0e"),
                            BaseClockSpeed = "2.5 GHz",
                            Brand = "Intel",
                            CacheSize = "18 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.4 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i5-12400F",
                            Price = 199.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("85e953ce-eae2-47e9-9481-28fb9b36d7d7"),
                            BaseClockSpeed = "3.6 GHz",
                            Brand = "AMD",
                            CacheSize = "19 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "AMD Radeon Graphics",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.4 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 3 5500",
                            Price = 159.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("10722dda-ee63-4bdb-9e60-4e4585ce623e"),
                            BaseClockSpeed = "3.3 GHz",
                            Brand = "Intel",
                            CacheSize = "12 MB",
                            CoreCount = 4,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.3 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i3-12100F",
                            Price = 109.98999999999999,
                            SocketType = "LGA 1700",
                            Tdp = "60W",
                            ThreadCount = 8
                        },
                        new
                        {
                            Id = new Guid("657602c4-5a87-4431-ad77-3eb17e2dbc7a"),
                            BaseClockSpeed = "3.8 GHz",
                            Brand = "AMD",
                            CacheSize = "36 MB",
                            CoreCount = 8,
                            IntegratedGraphics = "AMD Radeon Graphics Vega 8",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.6 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 7 5700G",
                            Price = 349.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 16
                        });
                });

            modelBuilder.Entity("Entities.Concrete.GPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseClockSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoostClockSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphicEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryBusWidth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerConnectors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Tdp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VramSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VramType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7c2d317-ed38-4d0c-9e17-c9fb58a11878"),
                            BaseClockSpeed = "2475 MHz",
                            BoostClockSpeed = "2490 MHz",
                            Brand = "MSI",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX™ 4070",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 11, 15),
                            MemoryBusWidth = "192 Bit",
                            ModelName = "VENTUS",
                            PowerConnectors = "8-pin + 6-pin",
                            Price = 499.99000000000001,
                            Tdp = "200W",
                            VramSize = "12GB",
                            VramType = "GDDR6X"
                        },
                        new
                        {
                            Id = new Guid("6df2957d-a948-4506-9c86-b26d176f63cc"),
                            BaseClockSpeed = "2400 MHz",
                            BoostClockSpeed = "2600 MHz",
                            Brand = "Gigabyte",
                            DisplayPorts = "DisplayPort x 3 (v2.1) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 7900 XTX",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 12, 15),
                            MemoryBusWidth = "384 Bit",
                            ModelName = "AORUS MASTER",
                            PowerConnectors = "8-pin x 3",
                            Price = 1399.99,
                            Tdp = "350W",
                            VramSize = "24GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("d51cc6cc-a02b-4980-8513-62177e751fdc"),
                            BaseClockSpeed = "2530 MHz",
                            BoostClockSpeed = "2575 MHz",
                            Brand = "ASUS",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 4070 Ti",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 12, 1),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "TUF Gaming",
                            PowerConnectors = "8-pin x 2",
                            Price = 799.99000000000001,
                            Tdp = "285W",
                            VramSize = "10GB",
                            VramType = "GDDR6X"
                        },
                        new
                        {
                            Id = new Guid("0e92b88a-d90d-43d2-9bf9-f06093a34e4c"),
                            BaseClockSpeed = "2300 MHz",
                            BoostClockSpeed = "2700 MHz",
                            Brand = "PowerColor",
                            DisplayPorts = "DisplayPort x 3 (v2.1) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 7800 XT",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 12, 1),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "Red Devil",
                            PowerConnectors = "8-pin x 3",
                            Price = 849.99000000000001,
                            Tdp = "330W",
                            VramSize = "16GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("ce532c24-81d2-4258-9212-a396d17265b7"),
                            BaseClockSpeed = "1410 MHz",
                            BoostClockSpeed = "1700 MHz",
                            Brand = "EVGA",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 3060 Ti",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 11, 17),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "GeForce RTX 3060 Ti",
                            PowerConnectors = "8-pin x 1",
                            Price = 399.99000000000001,
                            Tdp = "200W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("2a481176-a2fa-4673-b1ca-feb4040ee676"),
                            BaseClockSpeed = "2580 MHz",
                            BoostClockSpeed = "2670 MHz",
                            Brand = "XFX",
                            DisplayPorts = "DisplayPort x 2 (v2.0) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 6650 XT",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2023, 5, 10),
                            MemoryBusWidth = "128 Bit",
                            ModelName = "Speedster MERC 310",
                            PowerConnectors = "8-pin x 1",
                            Price = 349.99000000000001,
                            Tdp = "180W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("946b7c5a-2e29-4f51-b9c3-de11c818630d"),
                            BaseClockSpeed = "1720 MHz",
                            BoostClockSpeed = "1807 MHz",
                            Brand = "PNY",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 3050",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 1, 27),
                            MemoryBusWidth = "128 Bit",
                            ModelName = "XLR8 RTX 3050",
                            PowerConnectors = "6-pin x 1",
                            Price = 279.99000000000001,
                            Tdp = "130W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("04054bab-7e06-4bd4-80e9-6b7fea7260a8"),
                            BaseClockSpeed = "2100 MHz",
                            BoostClockSpeed = "2045 MHz",
                            Brand = "ASRock",
                            DisplayPorts = "DisplayPort x 2 (v1.4) HDMI™ x 2",
                            GraphicEngine = "Radeon RX 6600",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 8, 10),
                            MemoryBusWidth = "128 Bit",
                            ModelName = "Challenger D",
                            PowerConnectors = "6-pin x 1",
                            Price = 229.99000000000001,
                            Tdp = "130W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("7307efc2-8541-4a1e-b3f4-1a664629d684"),
                            BaseClockSpeed = "1580 MHz",
                            BoostClockSpeed = "1830 MHz",
                            Brand = "Inno3D",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 3070 Ti",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 6, 1),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "Twin X2 OC",
                            PowerConnectors = "8-pin x 2",
                            Price = 499.99000000000001,
                            Tdp = "290W",
                            VramSize = "8GB",
                            VramType = "GDDR6X"
                        },
                        new
                        {
                            Id = new Guid("0f3f6e76-4d49-459d-af0b-f4ca67d11293"),
                            BaseClockSpeed = "2420 MHz",
                            BoostClockSpeed = "2680 MHz",
                            Brand = "MSI",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 6700 XT",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2022, 3, 18),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "Radeon RX 6700 XT MECH 2X",
                            PowerConnectors = "8-pin x 1",
                            Price = 459.99000000000001,
                            Tdp = "230W",
                            VramSize = "12GB",
                            VramType = "GDDR6"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
