// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20240830142050_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Core.Entities.Concrete.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            CategoryName = "Cpu",
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 493, DateTimeKind.Utc).AddTicks(9374),
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("283387f2-0324-4ea3-b0cf-b0a39178ab04"),
                            CategoryName = "Gpu",
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 493, DateTimeKind.Utc).AddTicks(9481),
                            Order = 2
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Detail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4955233-181d-4736-9034-b5f7d1288ca3"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2160),
                            Order = 1,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "AMD",
                            PropertyId = new Guid("a8889346-e85e-4f0c-b29e-352d8d1a8666")
                        },
                        new
                        {
                            Id = new Guid("7bda6baf-7f28-42fc-b6bd-c614cc4bb543"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2236),
                            Order = 2,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "Ryzen",
                            PropertyId = new Guid("0c918516-42ed-4e73-b75e-5aa6eb270d2c")
                        },
                        new
                        {
                            Id = new Guid("8cc97f2f-e1e8-4b2f-96b5-a36d9a5385fb"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2238),
                            Order = 3,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "7000",
                            PropertyId = new Guid("5c28a010-3d4a-401a-a980-7c2d762023b9")
                        },
                        new
                        {
                            Id = new Guid("2b1c147b-7b7f-4cd3-bf34-5eb2f3fbb39b"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2250),
                            Order = 4,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "16",
                            PropertyId = new Guid("11f37990-fed5-41f0-b4e4-cf91f75f645e")
                        },
                        new
                        {
                            Id = new Guid("d95a055a-e201-4fbb-b478-a914818dc687"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2252),
                            Order = 5,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "32",
                            PropertyId = new Guid("3493f477-64d7-46d0-938d-4c2cf3106dc9")
                        },
                        new
                        {
                            Id = new Guid("2b690feb-8e47-4591-8175-12ff87441580"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2254),
                            Order = 6,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "4.2 GHz",
                            PropertyId = new Guid("d812fa95-4a9d-4a70-9944-1a86174d551b")
                        },
                        new
                        {
                            Id = new Guid("5ec0c301-19a8-4eb3-ab5a-4d369441f1c0"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2256),
                            Order = 7,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "5.7 GHz",
                            PropertyId = new Guid("329d6988-517d-4ba0-9c1a-d2dc68b04261")
                        },
                        new
                        {
                            Id = new Guid("8f58518e-8141-4d09-ae76-44d61a0fd47b"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2258),
                            Order = 8,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "AM5",
                            PropertyId = new Guid("5f6e3fa8-80ad-4074-a105-c9445ee8c019")
                        },
                        new
                        {
                            Id = new Guid("89b25603-fd05-436a-8112-33e9fc9b1706"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2261),
                            Order = 9,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "AMD Radeon™ Graphics",
                            PropertyId = new Guid("374dfd54-383b-49ad-b405-0ac099f3a027")
                        },
                        new
                        {
                            Id = new Guid("25d394cc-f0b3-4b2b-b4eb-5f5187685b5c"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2264),
                            Order = 10,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "DDR5",
                            PropertyId = new Guid("fb4afebc-c646-4602-9981-3c1f7920d20d")
                        },
                        new
                        {
                            Id = new Guid("e511ec95-de70-42b1-aba1-74bd8d973483"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2266),
                            Order = 11,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "120W",
                            PropertyId = new Guid("e31a2c4b-6e53-4278-9daa-dbf658431f3f")
                        },
                        new
                        {
                            Id = new Guid("fa79c502-d800-48ce-a06a-0ce3191c8ed1"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2268),
                            Order = 12,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "2023-02-28",
                            PropertyId = new Guid("a242284f-aaba-4acf-bfb1-55cc556ac85f")
                        },
                        new
                        {
                            Id = new Guid("f8cbda97-bd7d-4d90-b100-1930eb3fedec"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2270),
                            Order = 13,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "16 MB",
                            PropertyId = new Guid("a1a342d1-45e1-4e56-ad89-b08c021b02e3")
                        },
                        new
                        {
                            Id = new Guid("add10f96-5def-4077-b8e4-5e09be32b0d9"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2278),
                            Order = 14,
                            ProductId = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            PropValue = "128 MB",
                            PropertyId = new Guid("f6fbee42-b3c5-44f1-9d63-3c9b3136a060")
                        },
                        new
                        {
                            Id = new Guid("c0b4dd42-295a-45ea-a45a-8e253d962c9e"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2280),
                            Order = 1,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "AMD",
                            PropertyId = new Guid("a8889346-e85e-4f0c-b29e-352d8d1a8666")
                        },
                        new
                        {
                            Id = new Guid("f27c0a8f-fd35-4654-a298-a1036bf0b4c3"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2282),
                            Order = 2,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "Ryzen",
                            PropertyId = new Guid("0c918516-42ed-4e73-b75e-5aa6eb270d2c")
                        },
                        new
                        {
                            Id = new Guid("172076b4-9cfa-46ef-823f-83038a8985f6"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2284),
                            Order = 3,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "7000",
                            PropertyId = new Guid("5c28a010-3d4a-401a-a980-7c2d762023b9")
                        },
                        new
                        {
                            Id = new Guid("1b838db6-d646-40ba-9262-2cd0b4f841ba"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2288),
                            Order = 4,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "16",
                            PropertyId = new Guid("11f37990-fed5-41f0-b4e4-cf91f75f645e")
                        },
                        new
                        {
                            Id = new Guid("47f7ea99-cd27-4935-90f1-b41c3bb787c4"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2290),
                            Order = 5,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "32",
                            PropertyId = new Guid("3493f477-64d7-46d0-938d-4c2cf3106dc9")
                        },
                        new
                        {
                            Id = new Guid("caff9ff0-9b43-4818-8c07-102b6695a55c"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2291),
                            Order = 6,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "4.5 GHz",
                            PropertyId = new Guid("d812fa95-4a9d-4a70-9944-1a86174d551b")
                        },
                        new
                        {
                            Id = new Guid("5123f567-43c4-442a-8e9c-3666fcbeaad4"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2293),
                            Order = 7,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "5.7 GHz",
                            PropertyId = new Guid("329d6988-517d-4ba0-9c1a-d2dc68b04261")
                        },
                        new
                        {
                            Id = new Guid("1fadc053-00e4-4d68-b0a3-18492f24936a"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2295),
                            Order = 8,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "AM5",
                            PropertyId = new Guid("5f6e3fa8-80ad-4074-a105-c9445ee8c019")
                        },
                        new
                        {
                            Id = new Guid("0ef1b9fb-cfb7-4c30-9539-89a1f40845f7"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2297),
                            Order = 9,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "AMD Radeon™ Graphics",
                            PropertyId = new Guid("374dfd54-383b-49ad-b405-0ac099f3a027")
                        },
                        new
                        {
                            Id = new Guid("6e5ebac0-52d4-4269-9cdf-31eb80b2540e"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2299),
                            Order = 10,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "DDR5",
                            PropertyId = new Guid("fb4afebc-c646-4602-9981-3c1f7920d20d")
                        },
                        new
                        {
                            Id = new Guid("3aaf30f6-e5b3-4bb9-8219-8ee950d6e1ad"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2301),
                            Order = 11,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "170W",
                            PropertyId = new Guid("e31a2c4b-6e53-4278-9daa-dbf658431f3f")
                        },
                        new
                        {
                            Id = new Guid("4a3f109b-cce9-4c77-aa01-62bd490be62b"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2304),
                            Order = 12,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "2022-09-27",
                            PropertyId = new Guid("a242284f-aaba-4acf-bfb1-55cc556ac85f")
                        },
                        new
                        {
                            Id = new Guid("b83d3ff2-abac-472c-a55c-6ad3595a2795"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2306),
                            Order = 13,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "16 MB",
                            PropertyId = new Guid("a1a342d1-45e1-4e56-ad89-b08c021b02e3")
                        },
                        new
                        {
                            Id = new Guid("75ff4238-1429-44a3-8a02-5166f49c0bc0"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(2308),
                            Order = 14,
                            ProductId = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            PropValue = "64 MB",
                            PropertyId = new Guid("f6fbee42-b3c5-44f1-9d63-3c9b3136a060")
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("216ac5c2-f5ea-4a74-9fe0-889a9d7a6735"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1395),
                            Order = 1,
                            Price = 525.0,
                            ProductName = "AMD Ryzen™ 9 7950X3D",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("c861a5e8-187b-4a55-ad62-53f4f7574360"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1473),
                            Order = 2,
                            Price = 519.0,
                            ProductName = "AMD Ryzen™ 9 7950X",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("338ba77b-7b4e-4ea4-988f-9feea94a91d1"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1476),
                            Order = 3,
                            Price = 399.0,
                            ProductName = "AMD Ryzen™ 9 7900X3D",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("c9b9e9c4-6130-47ca-a5e5-1b23dab32074"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1478),
                            Order = 4,
                            Price = 350.0,
                            ProductName = "AMD Ryzen™ 9 7900X",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("0d2bab70-1fd5-402d-8b1a-de7f8d93ce96"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1490),
                            Order = 5,
                            Price = 369.0,
                            ProductName = "AMD Ryzen™ 9 7900",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("c547a2f5-764b-4b7d-a557-e819dc618f49"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1492),
                            Order = 6,
                            Price = 365.0,
                            ProductName = "AMD Ryzen™ 7 7800X3D",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("e241fb97-0f53-4534-b4d2-fdf2aadfc380"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1495),
                            Order = 7,
                            Price = 277.0,
                            ProductName = "AMD Ryzen™ 7 7700X",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("291d08a4-4546-4de3-b424-14d97373c207"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1497),
                            Order = 8,
                            Price = 280.0,
                            ProductName = "AMD Ryzen™ 7 7700",
                            SoldQuantity = 0,
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("91370f1c-19c1-4b3d-9b22-1e812ad211e8"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1499),
                            Order = 9,
                            Price = 195.0,
                            ProductName = "AMD Ryzen™ 5 7600X",
                            SoldQuantity = 0,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("1ccfc96a-419e-4940-bb49-8b477455292a"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1501),
                            Order = 10,
                            Price = 180.0,
                            ProductName = "AMD Ryzen™ 5 7600",
                            SoldQuantity = 0,
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("089fd623-946c-46e2-bee6-01771d0d7e57"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(1503),
                            Order = 11,
                            Price = 150.0,
                            ProductName = "AMD Ryzen™ 5 7500F",
                            SoldQuantity = 0,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8889346-e85e-4f0c-b29e-352d8d1a8666"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(565),
                            Order = 1,
                            PropName = "Brand"
                        },
                        new
                        {
                            Id = new Guid("0c918516-42ed-4e73-b75e-5aa6eb270d2c"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(647),
                            Order = 2,
                            PropName = "Family"
                        },
                        new
                        {
                            Id = new Guid("5c28a010-3d4a-401a-a980-7c2d762023b9"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(649),
                            Order = 3,
                            PropName = "Series"
                        },
                        new
                        {
                            Id = new Guid("11f37990-fed5-41f0-b4e4-cf91f75f645e"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(661),
                            Order = 4,
                            PropName = "Core count"
                        },
                        new
                        {
                            Id = new Guid("3493f477-64d7-46d0-938d-4c2cf3106dc9"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(663),
                            Order = 5,
                            PropName = "Thread count"
                        },
                        new
                        {
                            Id = new Guid("d812fa95-4a9d-4a70-9944-1a86174d551b"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(664),
                            Order = 6,
                            PropName = "Base clock speed"
                        },
                        new
                        {
                            Id = new Guid("329d6988-517d-4ba0-9c1a-d2dc68b04261"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(666),
                            Order = 7,
                            PropName = "Max turbo frequency"
                        },
                        new
                        {
                            Id = new Guid("5f6e3fa8-80ad-4074-a105-c9445ee8c019"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(668),
                            Order = 8,
                            PropName = "Socket type"
                        },
                        new
                        {
                            Id = new Guid("374dfd54-383b-49ad-b405-0ac099f3a027"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(678),
                            Order = 9,
                            PropName = "Integrated graphics"
                        },
                        new
                        {
                            Id = new Guid("fb4afebc-c646-4602-9981-3c1f7920d20d"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(680),
                            Order = 10,
                            PropName = "Memory support"
                        },
                        new
                        {
                            Id = new Guid("e31a2c4b-6e53-4278-9daa-dbf658431f3f"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(682),
                            Order = 11,
                            PropName = "Tdp"
                        },
                        new
                        {
                            Id = new Guid("a242284f-aaba-4acf-bfb1-55cc556ac85f"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(685),
                            Order = 12,
                            PropName = "Launch date"
                        },
                        new
                        {
                            Id = new Guid("6461d10f-fe71-449b-bdb2-880675603df8"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(687),
                            Order = 13,
                            PropName = "L1 cache"
                        },
                        new
                        {
                            Id = new Guid("a1a342d1-45e1-4e56-ad89-b08c021b02e3"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(688),
                            Order = 14,
                            PropName = "L2 cache"
                        },
                        new
                        {
                            Id = new Guid("f6fbee42-b3c5-44f1-9d63-3c9b3136a060"),
                            CategoryId = new Guid("49f07ca0-93dc-44f8-a1ed-46eed86007a8"),
                            LastUpdate = new DateTime(2024, 8, 30, 14, 20, 50, 494, DateTimeKind.Utc).AddTicks(690),
                            Order = 15,
                            PropName = "L3 cache"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Detail", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Image", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Product", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Property", b =>
                {
                    b.HasOne("Core.Entities.Concrete.Category", "Category")
                        .WithMany("Properties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Product", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
