// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(EfDbContext))]
    partial class EfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Entities.Concrete.CPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseClockSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoreCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntegratedGraphics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxTurboFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemorySupport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("SocketType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tdp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dba4c197-72f2-4c2a-a751-912919fd7811"),
                            BaseClockSpeed = "3.3 GHz",
                            Brand = "Intel",
                            CacheSize = "12 MB",
                            CoreCount = 4,
                            IntegratedGraphics = "Intel UHD Graphics 730",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.3 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i3-12100",
                            Price = 129.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "60W",
                            ThreadCount = 8
                        },
                        new
                        {
                            Id = new Guid("2716d97e-d59c-4342-916d-a930278b79eb"),
                            BaseClockSpeed = "4.0 GHz",
                            Brand = "AMD",
                            CacheSize = "40 MB",
                            CoreCount = 4,
                            IntegratedGraphics = "AMD Radeon Graphics Vega 6",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.6 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 3 5300G",
                            Price = 149.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 8
                        },
                        new
                        {
                            Id = new Guid("50a85ed7-2761-441d-9fc0-93aecdd1ffca"),
                            BaseClockSpeed = "2.5 GHz",
                            Brand = "Intel",
                            CacheSize = "18 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "Intel UHD Graphics 770",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.4 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i5-12400",
                            Price = 229.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("ec4512e8-ccce-48b5-86b1-1888d93c5cee"),
                            BaseClockSpeed = "3.7 GHz",
                            Brand = "AMD",
                            CacheSize = "38 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.6 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 5 5600X",
                            Price = 299.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("4e286288-9e84-40aa-b01b-9f7d6b8c859f"),
                            BaseClockSpeed = "3.6 GHz",
                            Brand = "Intel",
                            CacheSize = "25 MB",
                            CoreCount = 8,
                            IntegratedGraphics = "Intel UHD Graphics 770",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "5.2 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i7-12700K",
                            Price = 439.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "125W",
                            ThreadCount = 16
                        },
                        new
                        {
                            Id = new Guid("080e60f6-7c67-423f-9396-726f5166384d"),
                            BaseClockSpeed = "3.7 GHz",
                            Brand = "AMD",
                            CacheSize = "64 MB",
                            CoreCount = 12,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2020, 11, 19),
                            MaxTurboFrequency = "4.8 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 9 5900X",
                            Price = 549.99000000000001,
                            SocketType = "AM4",
                            Tdp = "105W",
                            ThreadCount = 24
                        },
                        new
                        {
                            Id = new Guid("e06f3824-7e4d-4b54-b96d-b772ad0b6e6a"),
                            BaseClockSpeed = "3.5 GHz",
                            Brand = "Intel",
                            CacheSize = "20 MB",
                            CoreCount = 8,
                            IntegratedGraphics = "Intel UHD Graphics 770",
                            LaunchDate = new DateOnly(2021, 3, 18),
                            MaxTurboFrequency = "5.3 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i9-11900K",
                            Price = 499.99000000000001,
                            SocketType = "LGA 1200",
                            Tdp = "125W",
                            ThreadCount = 16
                        },
                        new
                        {
                            Id = new Guid("ec8d2113-75a7-4694-bd7e-1e6cefb4ba66"),
                            BaseClockSpeed = "3.5 GHz",
                            Brand = "AMD",
                            CacheSize = "32 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "AMD Radeon Graphics",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.5 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 5 7600",
                            Price = 229.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("a7722d03-3619-4f92-94a6-afd43dc430da"),
                            BaseClockSpeed = "2.5 GHz",
                            Brand = "Intel",
                            CacheSize = "18 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.4 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i5-12400F",
                            Price = 199.99000000000001,
                            SocketType = "LGA 1700",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("08a0c8af-7396-4394-a32b-0ed201760864"),
                            BaseClockSpeed = "3.6 GHz",
                            Brand = "AMD",
                            CacheSize = "19 MB",
                            CoreCount = 6,
                            IntegratedGraphics = "AMD Radeon Graphics",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.4 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 3 5500",
                            Price = 159.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 12
                        },
                        new
                        {
                            Id = new Guid("fe96a5bd-f62a-4b0c-84f9-939af5c828c2"),
                            BaseClockSpeed = "3.3 GHz",
                            Brand = "Intel",
                            CacheSize = "12 MB",
                            CoreCount = 4,
                            IntegratedGraphics = "None",
                            LaunchDate = new DateOnly(2022, 1, 18),
                            MaxTurboFrequency = "4.3 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Core i3-12100F",
                            Price = 109.98999999999999,
                            SocketType = "LGA 1700",
                            Tdp = "60W",
                            ThreadCount = 8
                        },
                        new
                        {
                            Id = new Guid("861c47c1-b755-4dbd-b4d2-bf5b2c23194f"),
                            BaseClockSpeed = "3.8 GHz",
                            Brand = "AMD",
                            CacheSize = "36 MB",
                            CoreCount = 8,
                            IntegratedGraphics = "AMD Radeon Graphics Vega 8",
                            LaunchDate = new DateOnly(2022, 4, 19),
                            MaxTurboFrequency = "4.6 GHz",
                            MemorySupport = "DDR4-3200",
                            ModelName = "Ryzen 7 5700G",
                            Price = 349.99000000000001,
                            SocketType = "AM4",
                            Tdp = "65W",
                            ThreadCount = 16
                        });
                });

            modelBuilder.Entity("Entities.Concrete.GPU", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseClockSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoostClockSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphicEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemoryBusWidth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerConnectors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Tdp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VramSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VramType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7daf64c-07c3-4707-b34b-ef4726d0450c"),
                            BaseClockSpeed = "2475 MHz",
                            BoostClockSpeed = "2490 MHz",
                            Brand = "MSI",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX™ 4070",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 11, 15),
                            MemoryBusWidth = "192 Bit",
                            ModelName = "VENTUS",
                            PowerConnectors = "8-pin + 6-pin",
                            Price = 499.99000000000001,
                            Tdp = "200W",
                            VramSize = "12GB",
                            VramType = "GDDR6X"
                        },
                        new
                        {
                            Id = new Guid("97a7bd3a-647e-4a47-b27b-85104ec67dfc"),
                            BaseClockSpeed = "2400 MHz",
                            BoostClockSpeed = "2600 MHz",
                            Brand = "Gigabyte",
                            DisplayPorts = "DisplayPort x 3 (v2.1) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 7900 XTX",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 12, 15),
                            MemoryBusWidth = "384 Bit",
                            ModelName = "AORUS MASTER",
                            PowerConnectors = "8-pin x 3",
                            Price = 1399.99,
                            Tdp = "350W",
                            VramSize = "24GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("0af79d02-9c43-40e7-ac5e-cc8b278d899e"),
                            BaseClockSpeed = "2530 MHz",
                            BoostClockSpeed = "2575 MHz",
                            Brand = "ASUS",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 4070 Ti",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 12, 1),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "TUF Gaming",
                            PowerConnectors = "8-pin x 2",
                            Price = 799.99000000000001,
                            Tdp = "285W",
                            VramSize = "10GB",
                            VramType = "GDDR6X"
                        },
                        new
                        {
                            Id = new Guid("89824f68-8f43-4a35-91c3-681740046713"),
                            BaseClockSpeed = "2300 MHz",
                            BoostClockSpeed = "2700 MHz",
                            Brand = "PowerColor",
                            DisplayPorts = "DisplayPort x 3 (v2.1) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 7800 XT",
                            Interface = "PCIe 5.0 x16",
                            LaunchDate = new DateOnly(2023, 12, 1),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "Red Devil",
                            PowerConnectors = "8-pin x 3",
                            Price = 849.99000000000001,
                            Tdp = "330W",
                            VramSize = "16GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("7d20cbad-c22f-4847-9e0a-83226d7dddcd"),
                            BaseClockSpeed = "1410 MHz",
                            BoostClockSpeed = "1700 MHz",
                            Brand = "EVGA",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 3060 Ti",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 11, 17),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "GeForce RTX 3060 Ti",
                            PowerConnectors = "8-pin x 1",
                            Price = 399.99000000000001,
                            Tdp = "200W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("53ae14f0-9ff6-471d-a1d0-4fcd1e9fb3ca"),
                            BaseClockSpeed = "2580 MHz",
                            BoostClockSpeed = "2670 MHz",
                            Brand = "XFX",
                            DisplayPorts = "DisplayPort x 2 (v2.0) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 6650 XT",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2023, 5, 10),
                            MemoryBusWidth = "128 Bit",
                            ModelName = "Speedster MERC 310",
                            PowerConnectors = "8-pin x 1",
                            Price = 349.99000000000001,
                            Tdp = "180W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("2a9622d9-dc98-40fa-84d4-396e947267e1"),
                            BaseClockSpeed = "1720 MHz",
                            BoostClockSpeed = "1807 MHz",
                            Brand = "PNY",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 3050",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 1, 27),
                            MemoryBusWidth = "128 Bit",
                            ModelName = "XLR8 RTX 3050",
                            PowerConnectors = "6-pin x 1",
                            Price = 279.99000000000001,
                            Tdp = "130W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("a1beed27-1428-42e3-843d-290fcc9e516b"),
                            BaseClockSpeed = "2100 MHz",
                            BoostClockSpeed = "2045 MHz",
                            Brand = "ASRock",
                            DisplayPorts = "DisplayPort x 2 (v1.4) HDMI™ x 2",
                            GraphicEngine = "Radeon RX 6600",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 8, 10),
                            MemoryBusWidth = "128 Bit",
                            ModelName = "Challenger D",
                            PowerConnectors = "6-pin x 1",
                            Price = 229.99000000000001,
                            Tdp = "130W",
                            VramSize = "8GB",
                            VramType = "GDDR6"
                        },
                        new
                        {
                            Id = new Guid("67734159-2235-4179-8bbc-fe36c8dbed95"),
                            BaseClockSpeed = "1580 MHz",
                            BoostClockSpeed = "1830 MHz",
                            Brand = "Inno3D",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "GeForce RTX 3070 Ti",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2021, 6, 1),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "Twin X2 OC",
                            PowerConnectors = "8-pin x 2",
                            Price = 499.99000000000001,
                            Tdp = "290W",
                            VramSize = "8GB",
                            VramType = "GDDR6X"
                        },
                        new
                        {
                            Id = new Guid("40e077e2-b9a3-4b4c-82ad-d0fcc946ea9d"),
                            BaseClockSpeed = "2420 MHz",
                            BoostClockSpeed = "2680 MHz",
                            Brand = "MSI",
                            DisplayPorts = "DisplayPort x 3 (v1.4a) HDMI™ x 1",
                            GraphicEngine = "Radeon RX 6700 XT",
                            Interface = "PCIe 4.0 x16",
                            LaunchDate = new DateOnly(2022, 3, 18),
                            MemoryBusWidth = "256 Bit",
                            ModelName = "Radeon RX 6700 XT MECH 2X",
                            PowerConnectors = "8-pin x 1",
                            Price = 459.99000000000001,
                            Tdp = "230W",
                            VramSize = "12GB",
                            VramType = "GDDR6"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Entities.Concrete.Image", b =>
                {
                    b.HasOne("Entities.Concrete.CPU", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.GPU", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.CPU", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Entities.Concrete.GPU", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
